#!/bin/bash

cd /data/snoplus3/hunt-stokes/clean_multisite/Tl208_mc_information
cd cleaned_nhits
rm *.npy
cd ../energy
rm *.npy
cd ../itr
rm *.npy
cd ../position
rm *.npy
cd ../scaled_nhits
rm *.npy
cd ../time_residuals
rm *.npy
cd ..
rm *.npy

cd /data/snoplus3/hunt-stokes/clean_multisite/Tl210_mc_information
cd cleaned_nhits
rm *.npy
cd ../energy
rm *.npy
cd ../itr
rm *.npy
cd ../position
rm *.npy
cd ../scaled_nhits
rm *.npy
cd ../time_residuals
rm *.npy
cd ..
rm *.npy

cd /data/snoplus3/hunt-stokes/clean_multisite/Pa234m_mc_information
cd cleaned_nhits
rm *.npy
cd ../energy
rm *.npy
cd ../itr
rm *.npy
cd ../position
rm *.npy
cd ../scaled_nhits
rm *.npy
cd ../time_residuals
rm *.npy
cd ..
rm *.npy

cd /data/snoplus3/hunt-stokes/clean_multisite/BiPo212_mc_information
cd cleaned_nhits
rm *.npy
cd ../energy
rm *.npy
cd ../itr
rm *.npy
cd ../position
rm *.npy
cd ../scaled_nhits
rm *.npy
cd ../time_residuals
rm *.npy
cd ..
rm *.npy

cd /data/snoplus3/hunt-stokes/clean_multisite/BiPo214_mc_information
cd cleaned_nhits
rm *.npy
cd ../energy
rm *.npy
cd ../itr
rm *.npy
cd ../position
rm *.npy
cd ../scaled_nhits
rm *.npy
cd ../time_residuals
rm *.npy
cd ..
rm *.npy

cd /data/snoplus3/hunt-stokes/clean_multisite/B8_solar_nue_mc_information
cd cleaned_nhits
rm *.npy
cd ../energy
rm *.npy
cd ../itr
rm *.npy
cd ../position
rm *.npy
cd ../scaled_nhits
rm *.npy
cd ../time_residuals
rm *.npy
cd ..
rm *.npy

cd /data/snoplus3/hunt-stokes/clean_multisite/B8_solar_numu_mc_information
cd cleaned_nhits
rm *.npy
cd ../energy
rm *.npy
cd ../itr
rm *.npy
cd ../position
rm *.npy
cd ../scaled_nhits
rm *.npy
cd ../time_residuals
rm *.npy
cd ..
rm *.npy

cd /data/snoplus3/hunt-stokes/clean_multisite/gammas_2p2MeV_mc_information
cd cleaned_nhits
rm *.npy
cd ../energy
rm *.npy
cd ../itr
rm *.npy
cd ../position
rm *.npy
cd ../scaled_nhits
rm *.npy
cd ../time_residuals
rm *.npy
cd ..
rm *.npy

cd /data/snoplus3/hunt-stokes/clean_multisite/AlphaN_LAB_13C_mc_information
cd cleaned_nhits
rm *.npy
cd ../energy
rm *.npy
cd ../itr
rm *.npy
cd ../position
rm *.npy
cd ../scaled_nhits
rm *.npy
cd ../time_residuals
rm *.npy
cd ..
rm *.npy
